import turtle
a = turtle.Turtle()
a.shape('turtle')
a.pensize(5)
a.left(70)
a.forward(100)
a.right(130)
a.forward(100)
a.right(180)
a.forward(50)
a.left(60)
a.forward(40)
a.color('blue')
a.penup()
a.left(120)
a.forward(50)
a.left(60)
a.forward(90)
a.left(120)
a.pendown()
a.forward(90)
a.right(180)
a.forward(90)
a.left(120)
a.forward(70)
a.right(120)
a.forward(70)
a.left(120)
a.forward(90)
a.penup()
a.forward(70)
a.color('pink')
a.color('pink')
a.color('purple')
a.color('purple')
a.color('maroon')
a.color('maroon')
a.color('dark blue')
a.color('dark blue')
