##import turtle
##e = turtle.Turtle()
##e.shape('turtle')
##
##e.pensize(5)
##e.color("red")
##e.write('What color am I now? <3')
##e.left(45)
##e.forward(100)
##e.color("orange")
##e.write('What color am I now? <3')
##e.left(45)
##e.forward(100)
##e.color("yellow")
##e.write('What color am I now? <3')
##e.left(45)
##e.forward(100)
##e.color("green")
##e.write('What color am I now? <3')
##e.left(45)
##e.forward(100)
##e.color("blue")
##e.write('What color am I now? <3')
##e.left(45)
##e.forward(100)
##e.color("purple")
##e.write('What color am I now? <3')
##e.left(45)
##e.forward(100)
##e.color("teal")
##e.write('What color am I now? <3')
##e.left(45)
##e.forward(100)
##e.color("maroon")
##e.write('What color am I now? <3')
##e.left(45)
##e.forward(100)

import turtle
e = turtle.Turtle()
e.shape('turtle')

##e.penup()
##e.forward(100)
##e.write('I dont draw')
##e.backward(100)
##e.right(90)
##e.forward(20)
##e.left(90)
##e.pendown()
##e.forward(100)
##e.write('I like drawing now hehehehhehehe')
e.color("blue")
e.pensize(5)
e.forward(100)
e.backward(100)
e.left(90)
e.forward(50)
e.right(90)
e.forward(100)
e.backward(100)
