##import turtle
##t = turtle.Turtle()
##t.fillcolor('purple')
##t.begin_fill()
##t.forward(150)
##t.right(90)
##t.forward(150)
##t.right(90)
##t.forward(150)
##t.right(90)
##t.forward(150)
##t.right(90)
##t.end_fill()

##import turtle
##t = turtle.Turtle()
##t.shape('turtle')
##t.fillcolor('yellow')
##t.begin_fill()
##t.forward(100)
##t.right(60)
##t.forward(100)
##t.right(60)
##t.forward(100)
##t.right(60)
##t.forward(100)
##t.right(60)
##t.forward(100)
##t.right(60)
##t.forward(100)
##t.right(60)
##t.end_fill()
##t.color('red')
##t.pensize(5)
##t.forward(100)
##t.right(60)
##t.forward(100)
##t.right(60)
##t.forward(100)
##t.right(60)
##t.forward(100)
##t.right(60)
##t.forward(100)
##t.right(60)
##t.forward(100)
##t.right(60)


##import turtle
##t = turtle.Turtle()
##turtle.setup(600, 400)
##wn = turtle.Screen()
##wn.bgcolor("black")
##t = turtle.Pen()
##t.shape("turtle")
##t.penup()
##t.color("Chartreuse")
##t.backward(100)
##t.stamp()
##t.color('pink')
##t.forward(40)
##t.stamp()

import turtle
t = turtle.Turtle()
t.shape('classic')
t.penup()

t.backward(160)

t.color('Crimson')
t.forward(40)
t.stamp()

t.color('blue')
t.forward(40)
t.stamp()

t.color('cyan')
t.forward(40)
t.stamp()

t.color('purple')
t.forward(40)
t.stamp()

turtle.done()
